[package]
name = "discovery"
version = "0.1.0"
edition = "2021"

[dependencies]
capnp = { workspace = true }
capnp-rpc = { workspace = true }
futures   = { workspace = true }
log       = { workspace = true }
wit-bindgen = { workspace = true }
hex       = { workspace = true }
routing-key = { workspace = true }
system    = { path = "../../std/system" }

[lib]
crate-type = ["cdylib"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand = { workspace = true }

[dev-dependencies]
tokio      = { workspace = true, features = ["rt", "macros", "io-util"] }
tokio-util = { workspace = true, features = ["compat"] }

[build-dependencies]
capnpc = { workspace = true }
