[package]
name = "routing-key-probe"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
routing-key = { path = "../../../crates/guest/routing-key" }
wit-bindgen = { version = "=0.62.0", git = "https://github.com/wetware/wit-bindgen", rev = "025f95c294373c73e12eaee335577c81477d5a20" }

[lib]
crate-type = ["cdylib"]
