//! Shell cell — remote Glia REPL over Cap'n Proto.
//!
//! Evaluates Glia s-expressions in a persistent environment with
//! capability-scoped dispatch.  When served over vat RPC, the publisher
//! serves the shell capability; process lifetime remains publisher-owned.
//!
//! This is the "nREPL for Wetware": client sends text, cell evaluates,
//! result comes back.  State persists across evals (def sticks).

use std::cell::RefCell;
use std::collections::HashMap;
use std::future::Future;
use std::pin::Pin;
use std::rc::Rc;

use capnp::capability::Promise;
use capnp_rpc::pry;

use glia::effect::{EffectTarget, HostEffect, HostEffectResult};
use glia::eval::{self, Dispatch, Env, EvalOutcome};
use glia::{make_cap, HandledCapInner, Val};

use wasip2::exports::cli::run::Guest;

// Shared effect handler factories.
use caps::{
    get_graft_cap, make_host_handler, make_import_handler, make_routing_handler,
    membrane_capnp, routing_capnp, system_capnp, LoadRuntime,
};

// Shell-specific generated Cap'n Proto modules.
#[allow(dead_code)]
mod shell_capnp {
    include!(concat!(env!("OUT_DIR"), "/shell_capnp.rs"));
}

// Schema CID constants (generated by build.rs).
#[allow(dead_code)]
mod schema_ids {
    include!(concat!(env!("OUT_DIR"), "/schema_ids.rs"));
}

type Membrane = membrane_capnp::membrane::Client;

// ---------------------------------------------------------------------------
// Session — capability context for the shell cell
// ---------------------------------------------------------------------------

struct ShellSession {
    host: Option<system_capnp::host::Client>,
    routing: Option<routing_capnp::routing::Client>,
    initialized: bool,
}

// ---------------------------------------------------------------------------
// Dispatch
// ---------------------------------------------------------------------------

type HandlerFn = for<'a> fn(
    &'a [Val],
    &'a RefCell<ShellSession>,
) -> Pin<Box<dyn Future<Output = Result<Val, Val>> + 'a>>;

struct ShellDispatch<'s> {
    ctx: &'s RefCell<ShellSession>,
    table: &'s HashMap<&'static str, HandlerFn>,
}

impl<'s> Dispatch for ShellDispatch<'s> {
    fn call<'a>(
        &'a self,
        name: &'a str,
        args: &'a [Val],
    ) -> Pin<Box<dyn Future<Output = Result<Val, Val>> + 'a>> {
        Box::pin(async move {
            match self.table.get(name) {
                Some(handler) => handler(args, self.ctx).await,
                None => Err(Val::from(format!("{name}: command not found"))),
            }
        })
    }
}

fn build_dispatch() -> HashMap<&'static str, HandlerFn> {
    let mut t: HashMap<&'static str, HandlerFn> = HashMap::new();
    t.insert("help", |_, _| {
        Box::pin(std::future::ready(Ok(Val::Str(HELP_TEXT.to_string()))))
    });
    t
}

const HELP_TEXT: &str = "\
Remote Glia shell. Available commands:
  (perform host :id)       — peer identity
  (perform host :addrs)    — listen addresses
  (perform host :peers)    — connected peers
  (perform routing :find \"name\") — DHT lookup
  (help)                   — this message
  (perform :load \"path\")  — load bytes
  (perform :stdout value)  — write output
  (perform :exit nil)      — disconnect";

/// Default environmental effects are Rust-owned frames, never values placed
/// in the guest environment.  Guest `with-effect-handler` frames remain
/// dynamically innermost and may intentionally interpose.
fn host_effects(load_runtime: LoadRuntime, output: Rc<RefCell<String>>) -> Vec<HostEffect> {
    let load = Rc::new(move |data: Val| {
        let runtime = load_runtime.clone();
        Box::pin(async move { Ok(HostEffectResult::Resume(runtime.load_value(data).await?)) })
            as Pin<Box<dyn Future<Output = Result<HostEffectResult, Val>>>>
    });
    let stdout = Rc::new(move |data: Val| {
        let output = output.clone();
        Box::pin(async move {
            let text = match data { Val::Str(s) => s, other => format!("{other}") };
            let mut sink = output.borrow_mut();
            sink.push_str(&text);
            sink.push('\n');
            Ok(HostEffectResult::Resume(Val::Nil))
        }) as Pin<Box<dyn Future<Output = Result<HostEffectResult, Val>>>>
    });
    let exit = Rc::new(|_data: Val| {
        Box::pin(async { Ok(HostEffectResult::Exit) })
            as Pin<Box<dyn Future<Output = Result<HostEffectResult, Val>>>>
    });
    vec![
        HostEffect { target: EffectTarget::Keyword("load".into()), handler: load },
        HostEffect { target: EffectTarget::Keyword("stdout".into()), handler: stdout },
        HostEffect { target: EffectTarget::Keyword("exit".into()), handler: exit },
    ]
}

// ---------------------------------------------------------------------------
// Shell server — Cap'n Proto interface implementation
// ---------------------------------------------------------------------------

struct ShellImpl {
    env: Rc<RefCell<Env>>,
    ctx: Rc<RefCell<ShellSession>>,
    dispatch: HashMap<&'static str, HandlerFn>,
    ready: Rc<std::cell::Cell<bool>>,
    load_runtime: LoadRuntime,
}

#[allow(refining_impl_trait)]
impl shell_capnp::shell::Server for ShellImpl {
    fn eval(
        self: capnp::capability::Rc<Self>,
        params: shell_capnp::shell::EvalParams,
        mut results: shell_capnp::shell::EvalResults,
    ) -> Promise<(), capnp::Error> {
        results.get().set_output("");
        results.get().set_exit_requested(false);
        let text = match pry!(params.get()).get_text() {
            Ok(t) => match t.to_str() {
                Ok(s) => s.to_string(),
                Err(_) => {
                    results.get().set_result("invalid UTF-8 input");
                    results.get().set_is_error(true);
                    return Promise::ok(());
                }
            },
            Err(e) => {
                results.get().set_result(&format!("{e}"));
                results.get().set_is_error(true);
                return Promise::ok(());
            }
        };

        Promise::from_future(async move {
            // Check that the serve closure has finished initializing.
            if !self.ready.get() {
                results
                    .get()
                    .set_result("shell not ready (initialization in progress)");
                results.get().set_is_error(true);
                return Ok(());
            }

            if text.trim().is_empty() {
                results.get().set_result("");
                results.get().set_is_error(false);
                return Ok(());
            }

            // Parse
            let expr = match glia::read(&text) {
                Ok(expr) => expr,
                Err(e) => {
                    results.get().set_result(&format!("parse error: {e}"));
                    results.get().set_is_error(true);
                    return Ok(());
                }
            };

            // Capability handlers still use the standard dynamic wrappers.
            // Environmental host effects are Rust-owned frames: no guest-visible
            // handler value can be captured or invoked directly.
            let dispatch = ShellDispatch {
                ctx: &*self.ctx,
                table: &self.dispatch,
            };
            let output = Rc::new(RefCell::new(String::new()));
            let effects = host_effects(self.load_runtime.clone(), output.clone());
            match eval::eval_toplevel_with_host_effects(
                &expr,
                &mut self.env.borrow_mut(),
                &dispatch,
                &effects,
            ).await {
                Ok(EvalOutcome::Exit) => {
                    results.get().set_result("");
                    results.get().set_is_error(false);
                    results.get().set_exit_requested(true);
                }
                Ok(EvalOutcome::Value(Val::Nil)) => {
                    results.get().set_result("");
                    results.get().set_is_error(false);
                }
                Ok(EvalOutcome::Value(result)) => {
                    results.get().set_result(&format!("{result}"));
                    results.get().set_is_error(false);
                }
                Err(e) => {
                    // Unhandled `(throw ...)` arrives as Val::Effect{
                    // effect_type: "glia.exception", data: <err> } —
                    // peel before formatting so the user sees the inner
                    // structured error map.
                    let inner = glia::error::unwrap_thrown(&e).unwrap_or(&e);
                    let msg = glia::error::message(inner)
                        .map(str::to_string)
                        .unwrap_or_else(|| format!("{inner}"));
                    let formatted = match glia::error::type_tag(inner) {
                        Some(tag) => format!("[{tag}] {msg}"),
                        None => msg,
                    };
                    results.get().set_result(&formatted);
                    results.get().set_is_error(true);
                }
            }
            results.get().set_output(&*output.borrow());
            Ok(())
        })
    }
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

struct Shell;

impl Guest for Shell {
    fn run() -> Result<(), ()> {
        run_impl();
        Ok(())
    }
}

wasip2::cli::command::export!(Shell);

fn run_impl() {
    let env = Rc::new(RefCell::new(Env::new()));
    let ctx = Rc::new(RefCell::new(ShellSession {
        host: None,
        routing: None,
        initialized: false,
    }));
    let ready = Rc::new(std::cell::Cell::new(false));

    let load_runtime = caps::default_load_runtime();
    let shell_impl = ShellImpl {
        env: Rc::clone(&env),
        ctx: Rc::clone(&ctx),
        dispatch: build_dispatch(),
        ready: Rc::clone(&ready),
        load_runtime: load_runtime.clone(),
    };
    let client: shell_capnp::shell::Client = capnp_rpc::new_client(shell_impl);

    system::serve(client.client, |membrane: Membrane| async move {
        // 1. Graft the membrane to obtain capabilities.
        let graft_resp = membrane.graft_request().send().promise.await?;
        let results = graft_resp.get()?;

        // Find capabilities by name in the graft caps list.
        let caps = results.get_caps()?;
        let host: system_capnp::host::Client = get_graft_cap(&caps, "host")?;
        let routing: routing_capnp::routing::Client = get_graft_cap(&caps, "routing")?;

        // Populate session so cap handlers can access capabilities.
        {
            let mut s = ctx.borrow_mut();
            s.host = Some(host.clone());
            s.routing = Some(routing.clone());
            s.initialized = true;
        }

        // 2. Bind capabilities with intrinsic default handlers.  The handler
        // is carried by the cap, not exposed as `{cap}-handler` in Env.
        {
            let mut env = env.borrow_mut();
            let caps: [(&str, Val); 3] = [
                ("host", make_host_handler(host)),
                ("routing", make_routing_handler(routing)),
                ("import", make_import_handler(load_runtime)),
            ];
            for (name, handler) in caps {
                env.set(
                    name.to_string(),
                    make_cap(name, format!("shell:{name}"), std::rc::Rc::new(HandledCapInner {
                        handler,
                        export: std::rc::Rc::new(()),
                        descriptor: Vec::new(),
                    })),
                );
            }
        }

        // 3. Load the prelude (macro definitions only, no capability calls).
        {
            let mut env = env.borrow_mut();
            let prelude_forms = glia::read_many(glia::PRELUDE).expect("prelude: parse error");
            struct NoopDispatch;
            impl Dispatch for NoopDispatch {
                fn call<'a>(
                    &'a self,
                    name: &'a str,
                    _args: &'a [Val],
                ) -> Pin<Box<dyn Future<Output = Result<Val, Val>> + 'a>> {
                    Box::pin(std::future::ready(Err(Val::from(format!(
                        "{name}: not available"
                    )))))
                }
            }
            let noop = NoopDispatch;
            for form in &prelude_forms {
                let mut fut = Box::pin(eval::eval_toplevel(form, &mut env, &noop));
                let waker = std::task::Waker::noop();
                let mut cx = std::task::Context::from_waker(&waker);
                match fut.as_mut().poll(&mut cx) {
                    std::task::Poll::Ready(Ok(_)) => {}
                    std::task::Poll::Ready(Err(e)) => log::error!("prelude: {e}"),
                    std::task::Poll::Pending => log::error!("prelude: unexpected pending"),
                }
            }
        }

        ready.set(true);

        // Keep alive. The RPC system drives eval calls concurrently.
        std::future::pending::<Result<(), capnp::Error>>().await
    });
}
