//! Shell cell — remote Glia REPL over Cap'n Proto.
//!
//! Evaluates Glia s-expressions in a persistent environment with
//! capability-scoped dispatch.  When served over vat RPC, the publisher
//! serves the shell capability; process lifetime remains publisher-owned.
//!
//! This is the "nREPL for Wetware": client sends text, cell evaluates,
//! result comes back.  State persists across evals (def sticks).

use std::cell::RefCell;
use std::collections::HashMap;
use std::future::Future;
use std::pin::Pin;
use std::rc::Rc;

use capnp::capability::Promise;
use capnp_rpc::pry;

use glia::eval::{self, Dispatch, Env};
use glia::{Val, make_cap};

use wasip2::exports::cli::run::Guest;

// Shared effect handler factories.
use caps::{
    eval_load_async, get_graft_cap, make_host_handler, make_import_handler,
    make_routing_handler, membrane_capnp, routing_capnp, system_capnp, wrap_with_handlers,
};

// Shell-specific generated Cap'n Proto modules.
#[allow(dead_code)]
mod shell_capnp {
    include!(concat!(env!("OUT_DIR"), "/shell_capnp.rs"));
}

// Schema CID constants (generated by build.rs).
#[allow(dead_code)]
mod schema_ids {
    include!(concat!(env!("OUT_DIR"), "/schema_ids.rs"));
}

type Membrane = membrane_capnp::membrane::Client;

// ---------------------------------------------------------------------------
// Session — capability context for the shell cell
// ---------------------------------------------------------------------------

struct ShellSession {
    host: Option<system_capnp::host::Client>,
    routing: Option<routing_capnp::routing::Client>,
    initialized: bool,
}

// ---------------------------------------------------------------------------
// Dispatch
// ---------------------------------------------------------------------------

type HandlerFn = for<'a> fn(
    &'a [Val],
    &'a RefCell<ShellSession>,
) -> Pin<Box<dyn Future<Output = Result<Val, Val>> + 'a>>;

struct ShellDispatch<'s> {
    ctx: &'s RefCell<ShellSession>,
    table: &'s HashMap<&'static str, HandlerFn>,
}

impl<'s> Dispatch for ShellDispatch<'s> {
    fn call<'a>(
        &'a self,
        name: &'a str,
        args: &'a [Val],
    ) -> Pin<Box<dyn Future<Output = Result<Val, Val>> + 'a>> {
        Box::pin(async move {
            match self.table.get(name) {
                Some(handler) => handler(args, self.ctx).await,
                None => Err(Val::from(format!("{name}: command not found"))),
            }
        })
    }
}

fn build_dispatch() -> HashMap<&'static str, HandlerFn> {
    let mut t: HashMap<&'static str, HandlerFn> = HashMap::new();
    t.insert("load", |a, _| Box::pin(eval_load_async(a)));
    t.insert("help", |_, _| {
        Box::pin(std::future::ready(Ok(Val::Str(HELP_TEXT.to_string()))))
    });
    // Shell-specific exit: returns a sentinel keyword instead of process::exit.
    // The serve loop catches this and exits cleanly.
    t.insert("exit", |_, _| {
        Box::pin(std::future::ready(Ok(Val::Keyword("exit".into()))))
    });
    t
}

const HELP_TEXT: &str = "\
Remote Glia shell. Available commands:
  (perform host :id)       — peer identity
  (perform host :addrs)    — listen addresses
  (perform host :peers)    — connected peers
  (perform routing :find \"name\") — DHT lookup
  (help)                   — this message
  (exit)                   — disconnect";

// ---------------------------------------------------------------------------
// Shell server — Cap'n Proto interface implementation
// ---------------------------------------------------------------------------

struct ShellImpl {
    env: Rc<RefCell<Env>>,
    ctx: Rc<RefCell<ShellSession>>,
    dispatch: HashMap<&'static str, HandlerFn>,
    ready: Rc<std::cell::Cell<bool>>,
}

#[allow(refining_impl_trait)]
impl shell_capnp::shell::Server for ShellImpl {
    fn eval(
        self: capnp::capability::Rc<Self>,
        params: shell_capnp::shell::EvalParams,
        mut results: shell_capnp::shell::EvalResults,
    ) -> Promise<(), capnp::Error> {
        let text = match pry!(params.get()).get_text() {
            Ok(t) => match t.to_str() {
                Ok(s) => s.to_string(),
                Err(_) => {
                    results.get().set_result("invalid UTF-8 input");
                    results.get().set_is_error(true);
                    return Promise::ok(());
                }
            },
            Err(e) => {
                results.get().set_result(&format!("{e}"));
                results.get().set_is_error(true);
                return Promise::ok(());
            }
        };

        Promise::from_future(async move {
            // Check that the serve closure has finished initializing.
            if !self.ready.get() {
                results
                    .get()
                    .set_result("shell not ready (initialization in progress)");
                results.get().set_is_error(true);
                return Ok(());
            }

            if text.trim().is_empty() {
                results.get().set_result("");
                results.get().set_is_error(false);
                return Ok(());
            }

            // Parse
            let expr = match glia::read(&text) {
                Ok(expr) => expr,
                Err(e) => {
                    results.get().set_result(&format!("parse error: {e}"));
                    results.get().set_is_error(true);
                    return Ok(());
                }
            };

            // Wrap in effect handlers and evaluate
            let wrapped = wrap_with_handlers(&expr, &[]);
            let dispatch = ShellDispatch {
                ctx: &*self.ctx,
                table: &self.dispatch,
            };
            match eval::eval_toplevel(&wrapped, &mut self.env.borrow_mut(), &dispatch).await {
                Ok(Val::Nil) => {
                    results.get().set_result("");
                    results.get().set_is_error(false);
                }
                Ok(Val::Keyword(ref k)) if k == "exit" => {
                    results.get().set_result("exit");
                    results.get().set_is_error(false);
                }
                Ok(result) => {
                    results.get().set_result(&format!("{result}"));
                    results.get().set_is_error(false);
                }
                Err(e) => {
                    // Unhandled `(throw ...)` arrives as Val::Effect{
                    // effect_type: "glia.exception", data: <err> } —
                    // peel before formatting so the user sees the inner
                    // structured error map.
                    let inner = glia::error::unwrap_thrown(&e).unwrap_or(&e);
                    let msg = glia::error::message(inner)
                        .map(str::to_string)
                        .unwrap_or_else(|| format!("{inner}"));
                    let formatted = match glia::error::type_tag(inner) {
                        Some(tag) => format!("[{tag}] {msg}"),
                        None => msg,
                    };
                    results.get().set_result(&formatted);
                    results.get().set_is_error(true);
                }
            }
            Ok(())
        })
    }
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

struct Shell;

impl Guest for Shell {
    fn run() -> Result<(), ()> {
        run_impl();
        Ok(())
    }
}

wasip2::cli::command::export!(Shell);

fn run_impl() {
    let env = Rc::new(RefCell::new(Env::new()));
    let ctx = Rc::new(RefCell::new(ShellSession {
        host: None,
        routing: None,
        initialized: false,
    }));
    let ready = Rc::new(std::cell::Cell::new(false));

    let shell_impl = ShellImpl {
        env: Rc::clone(&env),
        ctx: Rc::clone(&ctx),
        dispatch: build_dispatch(),
        ready: Rc::clone(&ready),
    };
    let client: shell_capnp::shell::Client = capnp_rpc::new_client(shell_impl);

    system::serve(client.client, |membrane: Membrane| async move {
        // 1. Graft the membrane to obtain capabilities.
        let graft_resp = membrane.graft_request().send().promise.await?;
        let results = graft_resp.get()?;

        // Find capabilities by name in the graft caps list.
        let caps = results.get_caps()?;
        let host: system_capnp::host::Client = get_graft_cap(&caps, "host")?;
        let routing: routing_capnp::routing::Client = get_graft_cap(&caps, "routing")?;

        // Populate session so cap handlers can access capabilities.
        {
            let mut s = ctx.borrow_mut();
            s.host = Some(host.clone());
            s.routing = Some(routing.clone());
            s.initialized = true;
        }

        // 2. Bind cap values + effect handlers into the environment.
        {
            let mut env = env.borrow_mut();
            let caps: [(&str, Val); 3] = [
                ("host", make_host_handler(host)),
                ("routing", make_routing_handler(routing)),
                ("import", make_import_handler(caps::default_load_runtime())),
            ];
            for (name, handler) in caps {
                env.set(
                    name.to_string(),
                    make_cap(name, format!("shell:{name}"), std::rc::Rc::new(())),
                );
                env.set(format!("{name}-handler"), handler);
            }
        }

        // 3. Load the prelude (macro definitions only, no capability calls).
        {
            let mut env = env.borrow_mut();
            let prelude_forms = glia::read_many(glia::PRELUDE).expect("prelude: parse error");
            struct NoopDispatch;
            impl Dispatch for NoopDispatch {
                fn call<'a>(
                    &'a self,
                    name: &'a str,
                    _args: &'a [Val],
                ) -> Pin<Box<dyn Future<Output = Result<Val, Val>> + 'a>> {
                    Box::pin(std::future::ready(Err(Val::from(format!(
                        "{name}: not available"
                    )))))
                }
            }
            let noop = NoopDispatch;
            for form in &prelude_forms {
                let mut fut = Box::pin(eval::eval_toplevel(form, &mut env, &noop));
                let waker = std::task::Waker::noop();
                let mut cx = std::task::Context::from_waker(&waker);
                match fut.as_mut().poll(&mut cx) {
                    std::task::Poll::Ready(Ok(_)) => {}
                    std::task::Poll::Ready(Err(e)) => log::error!("prelude: {e}"),
                    std::task::Poll::Pending => log::error!("prelude: unexpected pending"),
                }
            }
        }

        ready.set(true);

        // Keep alive. The RPC system drives eval calls concurrently.
        std::future::pending::<Result<(), capnp::Error>>().await
    });
}
