//! Default kernel IPFS CID
//!
//! This module provides the IPFS CID for the default-kernel WASM example.
//! The CID is read from Cargo's target directory (`default-config.cid`) at build time.
//!
//! To rebuild the default config and regenerate the CID file, run:
//! ```bash
//! make default-config
//! ```
//!
//! # Example
//!
//! ```no_run
//! use ww::default_kernel::DEFAULT_KERNEL_CID;
//!
//! // Use the CID to run the default kernel from IPFS
//! // ww run DEFAULT_KERNEL_CID
//! ```

/// Default kernel IPFS CID (read from generated .cid file)
///
/// This is the root CID of the default-kernel directory in IPFS.
/// The CID is stored in Cargo's target directory as `default-config.cid`
/// (generated by `make default-config`).
/// To rebuild the default config and regenerate it, run `make default-config`.
///
/// This constant is set via `cargo:rustc-env` in build.rs (which reads the .cid file)
/// and accessed using `env!()`. If the file doesn't exist, this will be an empty string.
pub const DEFAULT_KERNEL_CID: &str = env!("DEFAULT_KERNEL_CID");
